"""Convert a teammate-annotated .xlsx into the 10-column contrastive TSV the pipeline eats.

The ONE rule this enforces (FORMAT_SPEC, and the prerequisite for RESEARCH_PLAN's Delta
attribution): src_clean must be src_noisy with ONLY noise_span -> noise_std replaced.
Anything else -- an added comma, a reworded phrase, a dropped emoji -- leaks non-noise
variation into Delta = score(clean) - score(noisy) and makes RQ1/RQ2 uninterpretable.

So src_clean is REGENERATED by splicing, never trusted from the sheet. Every row whose
sheet value disagrees is written to a review file so the annotator can check our splice
against their intent. Rows that cannot be spliced at all are quarantined, not guessed.

  python data/convert_xlsx.py data/raw/tableB_*.xlsx --out data/contrastive_B.tsv

Originals in data/raw/ are never modified.
"""
import argparse
import os
import re
import sys
import unicodedata

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from lib_data import REQUIRED_COLS  # the subset the pipeline insists on

# Full FORMAT_SPEC column order. REQUIRED_COLS is a subset (the pipeline tolerates extras);
# we emit all ten so noise_std/source_meta survive for R3 and provenance.
COLS = ["uid", "table", "category", "src_noisy", "src_clean", "ref_en",
        "noise_span", "noise_gold_en", "noise_std", "source_meta"]
_missing = [c for c in REQUIRED_COLS if c not in COLS]
if _missing:
    raise SystemExit(f"COLS is out of sync with lib_data.REQUIRED_COLS: missing {_missing}")

SEP = "‖"  # the double-vertical-bar separator FORMAT_SPEC uses for multi-span cells
CATS = ("HOM", "PYA", "NEO", "MIX")
MIN_LEN, MAX_LEN = 8, 60  # RESEARCH_PLAN 5 translatability gate

# De-identification (project data-ethics rule): these must never reach a result file.
AT = re.compile(r"@[\w一-鿿\-_]{2,}")
URL = re.compile(r"https?://\S+|www\.\S+")
PHONE = re.compile(r"\b1[3-9]\d{9}\b")

_EMOJI = re.compile("[\U0001F000-\U0001FAFF☀-➿️]+")
_PUNCT = re.compile(r"[　\s。．.！!？?，,、；;：:～~…—\-\"“”'‘’（）()【】《》]")


def _core(s):
    """Text with punctuation/whitespace/emoji stripped — for classifying how big a diff is."""
    return _PUNCT.sub("", _EMOJI.sub("", unicodedata.normalize("NFKC", s)))


def splice(src_noisy, spans, stds):
    """src_clean per FORMAT_SPEC: replace each span with its standard form, nothing else."""
    out = src_noisy
    for a, b in zip(spans, stds):
        out = out.replace(a, b)
    return out


def read_sheet(path):
    import openpyxl

    ws = openpyxl.load_workbook(path, data_only=True).worksheets[0]
    rows = list(ws.iter_rows(values_only=True))
    header = [str(c).strip() if c is not None else "" for c in rows[0]]
    if header != COLS:
        raise SystemExit(f"{path}: header mismatch\n  got  {header}\n  want {COLS}")
    recs = []
    for i, r in enumerate(rows[1:], start=2):
        d = {k: (str(v).strip() if v is not None else "") for k, v in zip(header, r)}
        if any(d[c] for c in COLS):
            d["_row"] = i
            recs.append(d)
    return recs


def classify(d):
    """Return (spliced_clean, verdict, note). verdict: ok | punct | rewritten | BLOCK:<why>."""
    spans = [s.strip() for s in d["noise_span"].split(SEP) if s.strip()]
    stds = [s.strip() for s in d["noise_std"].split(SEP) if s.strip()]
    if not spans or not stds:
        return "", "BLOCK", "noise_span or noise_std empty"
    if len(spans) != len(stds):
        return "", "BLOCK", f"span/std count mismatch ({len(spans)} vs {len(stds)})"
    missing = [s for s in spans if s not in d["src_noisy"]]
    if missing:
        return "", "BLOCK", f"noise_span not found in src_noisy: {missing}"
    if d["category"] not in CATS:
        return "", "BLOCK", f"bad category {d['category']!r}"

    spl = splice(d["src_noisy"], spans, stds)
    if spl == d["src_noisy"]:
        # noise_std == noise_span, so src_clean would equal src_noisy and Delta is 0 by
        # construction — the row is not a contrastive pair and can measure nothing.
        # taxonomy.md 7.1: a MIX proper noun with no Chinese standard form is excluded
        # with reason code NOSTD; for HOM/PYA/NEO it means noise_std was never filled in.
        return "", "BLOCK", "NOSTD: noise_std == noise_span, so src_clean == src_noisy (taxonomy 7.1)"
    sheet = d["src_clean"]
    if spl == sheet:
        return spl, "ok", ""
    if _core(spl) == _core(sheet):
        return spl, "punct", "sheet differs only in punctuation/whitespace/emoji"
    added = "".join(sorted(set(_core(sheet)) - set(_core(spl))))
    return spl, "rewritten", f"sheet rewrote body; chars absent from src_noisy: {added or '(none)'}"


def deident(d):
    hits = []
    for col in ("src_noisy", "src_clean", "ref_en"):
        for name, rx in (("@user", AT), ("url", URL), ("phone", PHONE)):
            if rx.search(d[col]):
                hits.append(f"{col}:{name}")
    return hits


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("xlsx")
    ap.add_argument("--out", required=True, help="output TSV path")
    ap.add_argument("--review-dir", default=None, help="default: <out dir>/review")
    ap.add_argument("--allow-rewritten", action="store_true",
                    help="emit rows whose sheet src_clean was a rewrite (our splice is used "
                         "regardless; this only decides whether they reach the TSV)")
    args = ap.parse_args()

    recs = read_sheet(args.xlsx)
    review_dir = args.review_dir or os.path.join(os.path.dirname(args.out) or ".", "review")
    os.makedirs(review_dir, exist_ok=True)
    stem = os.path.splitext(os.path.basename(args.out))[0]

    kept, blocked, changed, flags = [], [], [], []
    seen_uid, seen_src = {}, {}
    for d in recs:
        rid = f"row{d['_row']}/{d['uid'] or '?'}"
        spl, verdict, note = classify(d)
        if verdict == "BLOCK":
            blocked.append((rid, note, d))
            continue

        for h in deident(d):
            flags.append((rid, f"de-identification: {h}"))
        if d["uid"] in seen_uid:
            flags.append((rid, f"duplicate uid (first at {seen_uid[d['uid']]})"))
        seen_uid.setdefault(d["uid"], rid)
        if d["src_noisy"] in seen_src:
            flags.append((rid, f"duplicate src_noisy (first at {seen_src[d['src_noisy']]})"))
        seen_src.setdefault(d["src_noisy"], rid)
        if d["uid"][2:5] != d["category"]:
            flags.append((rid, f"uid says {d['uid'][2:5]!r} but category column says {d['category']!r}"))
        n = len(d["src_noisy"])
        if not MIN_LEN <= n <= MAX_LEN:
            flags.append((rid, f"src_noisy length {n} outside [{MIN_LEN},{MAX_LEN}]"))
        if len([g for g in d["noise_gold_en"].split(SEP) if g.strip()]) > 4:
            flags.append((rid, "noise_gold_en has more than gold+3 variants"))

        if verdict != "ok":
            changed.append((rid, verdict, note, d["src_clean"], spl))
        if verdict == "rewritten" and not args.allow_rewritten:
            continue
        out = dict(d)
        out["src_clean"] = spl  # spec-compliant by construction
        kept.append(out)

    with open(args.out, "w", encoding="utf-8") as f:
        f.write("\t".join(COLS) + "\n")
        for d in kept:
            f.write("\t".join(d[c].replace("\t", " ").replace("\n", " ") for c in COLS) + "\n")

    rp = os.path.join(review_dir, f"{stem}_review.tsv")
    with open(rp, "w", encoding="utf-8") as f:
        f.write("uid_row\tverdict\tnote\tsheet_src_clean\tspliced_src_clean\n")
        for rid, v, note, sheet, spl in changed:
            f.write(f"{rid}\t{v}\t{note}\t{sheet}\t{spl}\n")
    bp = os.path.join(review_dir, f"{stem}_blocked.tsv")
    with open(bp, "w", encoding="utf-8") as f:
        f.write("uid_row\treason\tsrc_noisy\tnoise_span\tnoise_std\n")
        for rid, note, d in blocked:
            f.write(f"{rid}\t{note}\t{d['src_noisy']}\t{d['noise_span']}\t{d['noise_std']}\n")
    fp = os.path.join(review_dir, f"{stem}_flags.tsv")
    with open(fp, "w", encoding="utf-8") as f:
        f.write("uid_row\tflag\n")
        for rid, msg in flags:
            f.write(f"{rid}\t{msg}\n")

    import collections
    cats = collections.Counter(d["category"] for d in kept)
    vd = collections.Counter(v for _, v, _, _, _ in changed)
    print(f"read {len(recs)} rows from {args.xlsx}")
    print(f"  sheet src_clean already spec-compliant : {len(recs) - len(blocked) - len(changed)}")
    print(f"  punctuation-only diff (splice used)    : {vd['punct']}")
    print(f"  body REWRITTEN by annotator            : {vd['rewritten']}"
          f"{'  <- emitted (--allow-rewritten)' if args.allow_rewritten else '  <- EXCLUDED'}")
    print(f"  blocked (cannot splice)                : {len(blocked)}")
    print(f"  other flags                            : {len(flags)}")
    print(f"\nwrote {len(kept)} rows -> {args.out}")
    print(f"  per category: " + "  ".join(f"{c}={cats.get(c, 0)}" for c in CATS))
    print(f"review: {rp}\nblocked: {bp}\nflags: {fp}")


if __name__ == "__main__":
    main()
